#!/bin/bash

#################################################################################
#                                   _       _        __                         #
#               _ __ __ _ ___ _ __ (_)     (_)_ __  / _| ___                    #
#              | '__/ _` / __| '_ \| |_____| | '_ \| |_ / _ \                   #
#              | | | (_| \__ \ |_) | |_____| | | | |  _| (_) |                  #
#              |_|  \__,_|___/ .__/|_|     |_|_| |_|_|  \___/                   #
#                            |_|                                                #
#                                                                               #
#                                                                               #
# MIT License                                                                   #
# Copyright (c) 2019-2024 Massimo Pissarello                                    #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
# The above copyright notice and this permission notice shall be included in    #
# all copies or substantial portions of the Software.                           #
#                                                                               #
#################################################################################


COLOR=`shuf -i91-96 -n1`
echo && echo && echo
echo -e '\e[0m\e['$COLOR'm                      RASPI-INFO-CHECK'
echo -e '\e[0m\e[0m     How many seconds do you want to update the data?'
echo -e '                  Press a key from 1 to 9.'
echo -e '    If you want to leave the default time (5 seconds)'
read -p "             press any letter key (no number). " -n 1 -r -s
echo

if ! [[ $REPLY =~ ^[1-9]$ ]]; then
	REPLY=5
fi

echo
echo -e '\e[0m\e['$COLOR'm                  Press CTRL + C to exit'
echo -e '\e[0m'
echo "   Time     Load average    Temp    Clock  FreeMem  Volt"

while true; do
	let ++Counter
	if [ ${Counter} -eq 15 ]; then
		Counter=0; fi
	LoadAv=$(uptime | awk -F'[a-z]:' '{print $2}')
	Temp=$(vcgencmd measure_temp | cut -f2 -d=)
	Clockspeed=$(vcgencmd measure_clock arm | awk -F"=" '{printf ("%0.0f",$2/1000000); }' )
	CoreVolt=$(vcgencmd measure_volts | cut -f2 -d= | sed 's/000//')
	FreeMem=$(free --mega | grep '^Mem' | awk '{ print $4 }')
	echo -e " $(date '+%H:%M:%S')${LoadAv}  ${Temp} $(printf '%4s' ${Clockspeed})MHz   ${FreeMem}   ${CoreVolt}"
	sleep $REPLY
done
